package io.openliberty.tools.gradle;

import java.io.File
import java.io.FileInputStream;
import java.util.Properties;

import org.junit.BeforeClass
import org.junit.Test
import org.apache.commons.io.FileUtils
import io.openliberty.tools.common.plugins.util.OSUtil

public class TestCreateWithInlineProperties extends AbstractIntegrationTest{
    static File sourceDir = new File("build/resources/test/server-config-files")
    static File testBuildDir = new File(integTestDir, "/test-create-with-inline-properties")
    static String buildFilename = "testCreateLibertyInlineProperties.gradle"

    @BeforeClass
    public static void setup() {
        createDir(testBuildDir)
        createTestProject(testBuildDir, sourceDir, buildFilename, true)
    }

    @Test
    public void test_create_with_inline_properties() {

        runTasks(testBuildDir, 'libertyCreate')

        def bootstrapFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/bootstrap.properties")
        def jvmOptionsFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/jvm.options")
        def configFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/server.xml")
        def serverEnvFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/server.env")
        def libertyConfigVarOverridesFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/configDropins/overrides/liberty-plugin-variable-config.xml")
        def libertyConfigVarDefaultsFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/configDropins/defaults/liberty-plugin-variable-config.xml")

        assert bootstrapFile.exists() : "file not found"
        assert jvmOptionsFile.exists() : "file not found"
        assert configFile.exists() : "file not found"
        assert serverEnvFile.exists() : "file not found"
        assert libertyConfigVarOverridesFile.exists() : "file not found"
        assert libertyConfigVarDefaultsFile.exists() : "file not found"

        // Verify file contents appear in this overall order (but order within section is not guaranteed)
        //
        // Gradle jvmOptions config
        // -Xmx512m
        //
        // Gradle properties
        // -Xms128m
        // -Dmy.dup.jvmoption=This is the value  (should only appear once even though specified in both)
        // -Xmx2048m

        String fileContents = jvmOptionsFile.text.replaceAll("\r","");
        String[] fileContentsArray = fileContents.split("\\n");
        assert fileContentsArray.length == 5 : "fileContentsArray.length="+fileContentsArray.length+" fileContents: "+fileContents
        assert fileContentsArray[0].equals("# Generated by liberty-gradle-plugin") : "jvm inline options did not copy properly "+fileContentsArray[0]
        assert fileContentsArray[1].endsWith("-Xmx512m") : "jvm inline option expected -Xmx512m, but found: "+fileContentsArray[4]

        boolean xms128mFound = false
        boolean xmx2048Found = false
        boolean myDupJvmOptionFound = false
        boolean unrecognizedOptionFound = false
        String unrecognizedOption = ""

        for (int i=2; i < 5; i++) {
            if (fileContentsArray[i].equals("-Xms128m")) {
                assert !xms128mFound : "jvm inline option -Xms128m found more than once"
                xms128mFound = true
            } else if (fileContentsArray[i].equals("-Xmx2048m")) {
                assert !xmx2048Found : "jvm inline option -Xmx2048m found more than once"
                xmx2048Found = true
            } else if (fileContentsArray[i].equals("-Dmy.dup.jvmoption=This is the value")) {
                assert !myDupJvmOptionFound : "jvm inline option -Dmy.dup.jvmoption found more than once"
                myDupJvmOptionFound = true                
            } else {
                unrecognizedOptionFound = true
                unrecognizedOption = fileContentsArray[i]
            }
        }

        assert !unrecognizedOptionFound : "Unrecognized jvm inline option found: "+unrecognizedOption
        assert xms128mFound : "Expected jvm inline option -Xms128m not found"
        assert xmx2048Found : "Expected jvm inline option -Xmx2048m not found"
        assert myDupJvmOptionFound : "Expected jvm inline option -Dmy.dup.jvmoptio not found"

        assert FileUtils.contentEquals(configFile, new File("build/testBuilds/test-create-with-inline-properties/src/main/liberty/config/server.xml")) : "server.xml file did not copy properly"


        // Verify the bootstrap.properties file contains correct info from inline config
        FileInputStream input1 = new FileInputStream(bootstrapFile);

        Properties prop = new Properties();
        prop.load( input1 );
        String value1 = prop.getProperty("default.http.port");
        assert value1 != null : "bootstrap property not found"
        assert value1.equals("9083") : "bootstrap property has incorrect value"

        value1 = prop.getProperty("default.https.port");
        assert value1 != null : "bootstrap property not found"
        assert value1.equals("9474") : "bootstrap property has incorrect value"


        FileInputStream input2 = new FileInputStream(serverEnvFile);

        prop = new Properties();
        prop.load( input2 );
        assert prop.size() == 3 : "expected 3 properties in server.env file but found "+prop.size()
        String value2 = prop.getProperty("some.env.var");
        assert value2 != null && value2.equals("someValue") : "some.env.var property not found in server.env file"
        value2 = prop.getProperty("another.env.var");
        assert value2 != null && value2.equals("anotherValue") : "another.env.var property not found in server.env file"
        // if no server.env file is specified in configuration and mergeServerEnv is not set to true, 
        // the keystore_password is still preserved when present in the default server.env file and not specified in a property
        value2 = prop.getProperty("keystore_password");
        assert value2 != null : "keystore_password property not found in server.env file"

        assert libertyConfigVarOverridesFile.text.contains("name=\"someVar\"") : "configDropins/overrides/liberty-plugin-variable-config.xml does not contain expected variable: "+libertyConfigVarOverridesFile.text
        assert libertyConfigVarOverridesFile.text.contains("value=\"someValue\"") : "configDropins/overrides/liberty-plugin-variable-config.xml does not contain expected variable: "+libertyConfigVarOverridesFile.text

        assert libertyConfigVarOverridesFile.text.contains("name=\"my.custom.var\"") : "configDropins/overrides/liberty-plugin-variable-config.xml does not contain expected variable: "+libertyConfigVarOverridesFile.text
        assert libertyConfigVarOverridesFile.text.contains("value=\"myCustomValue\"") : "configDropins/overrides/liberty-plugin-variable-config.xml does not contain expected variable: "+libertyConfigVarOverridesFile.text

        assert libertyConfigVarDefaultsFile.text.contains("name=\"someDefaultVar\"") : "configDropins/defaults/liberty-plugin-variable-config.xml does not contain expected variable: "+ libertyConfigVarDefaultsFile.text
        assert libertyConfigVarDefaultsFile.text.contains("defaultValue=\"someDefaultValue\"") : "configDropins/defaults/liberty-plugin-variable-config.xml does not contain expected variable: "+ libertyConfigVarDefaultsFile.text

    }
}
