package io.openliberty.tools.gradle;

import java.io.File
import java.io.FileInputStream;
import java.util.Properties;

import org.junit.BeforeClass
import org.junit.Test
import org.apache.commons.io.FileUtils
import io.openliberty.tools.common.plugins.util.OSUtil

public class TestCreateWithInlineProperties extends AbstractIntegrationTest{
    static File sourceDir = new File("build/resources/test/server-config-files")
    static File testBuildDir = new File(integTestDir, "/test-create-with-inline-properties")
    static String buildFilename = "testCreateLibertyInlineProperties.gradle"

    @BeforeClass
    public static void setup() {
        createDir(testBuildDir)
        createTestProject(testBuildDir, sourceDir, buildFilename, true)
    }

    @Test
    public void test_create_with_inline_properties() {

        runTasks(testBuildDir, 'libertyCreate')

        def bootstrapFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/bootstrap.properties")
        def jvmOptionsFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/jvm.options")
        def configFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/server.xml")
        def serverEnvFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/server.env")
        def libertyConfigVarOverridesFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/configDropins/overrides/liberty-plugin-variable-config.xml")
        def libertyConfigVarDefaultsFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/configDropins/defaults/liberty-plugin-variable-config.xml")

        assert bootstrapFile.exists() : "file not found"
        assert jvmOptionsFile.exists() : "file not found"
        assert configFile.exists() : "file not found"
        assert serverEnvFile.exists() : "file not found"
        assert libertyConfigVarOverridesFile.exists() : "file not found"
        assert libertyConfigVarDefaultsFile.exists() : "file not found"

        if (OSUtil.isWindows()) {
            assert jvmOptionsFile.text.startsWith("# Generated by liberty-gradle-plugin\r\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
            assert jvmOptionsFile.text.endsWith("-Xmx2048m\r\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
            assert jvmOptionsFile.text.contains("-Xmx512m\r\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
            assert jvmOptionsFile.text.contains("-Xms128m\r\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
        } else {
            assert jvmOptionsFile.text.startsWith("# Generated by liberty-gradle-plugin\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
            assert jvmOptionsFile.text.endsWith("-Xmx2048m\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
            assert jvmOptionsFile.text.contains("-Xmx512m\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
            assert jvmOptionsFile.text.contains("-Xms128m\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
        }

        assert FileUtils.contentEquals(configFile, new File("build/testBuilds/test-create-with-inline-properties/src/main/liberty/config/server.xml")) : "server.xml file did not copy properly"


        // Verify the bootstrap.properties file contains correct info from inline config
        FileInputStream input1 = new FileInputStream(bootstrapFile);

        Properties prop = new Properties();
        prop.load( input1 );
        String value1 = prop.getProperty("default.http.port");
        assert value1 != null : "bootstrap property not found"
        assert value1.equals("9083") : "bootstrap property has incorrect value"

        value1 = prop.getProperty("default.https.port");
        assert value1 != null : "bootstrap property not found"
        assert value1.equals("9474") : "bootstrap property has incorrect value"


        FileInputStream input2 = new FileInputStream(serverEnvFile);

        prop = new Properties();
        prop.load( input2 );
        assert prop.size() == 3 : "expected 3 properties in server.env file but found "+prop.size()
        String value2 = prop.getProperty("some.env.var");
        assert value2 != null && value2.equals("someValue") : "some.env.var property not found in server.env file"
        value2 = prop.getProperty("another.env.var");
        assert value2 != null && value2.equals("anotherValue") : "another.env.var property not found in server.env file"
        // if no server.env file is specified in configuration and mergeServerEnv is not set to true, 
        // the keystore_password is still preserved when present in the default server.env file and not specified in a property
        value2 = prop.getProperty("keystore_password");
        assert value2 != null : "keystore_password property not found in server.env file"

        assert libertyConfigVarOverridesFile.text.contains("name=\"someVar\"") : "configDropins/overrides/liberty-plugin-variable-config.xml does not contain expected variable: "+libertyConfigVarOverridesFile.text
        assert libertyConfigVarOverridesFile.text.contains("value=\"someValue\"") : "configDropins/overrides/liberty-plugin-variable-config.xml does not contain expected variable: "+libertyConfigVarOverridesFile.text

        assert libertyConfigVarOverridesFile.text.contains("name=\"my.custom.var\"") : "configDropins/overrides/liberty-plugin-variable-config.xml does not contain expected variable: "+libertyConfigVarOverridesFile.text
        assert libertyConfigVarOverridesFile.text.contains("value=\"myCustomValue\"") : "configDropins/overrides/liberty-plugin-variable-config.xml does not contain expected variable: "+libertyConfigVarOverridesFile.text

        assert libertyConfigVarDefaultsFile.text.contains("name=\"someDefaultVar\"") : "configDropins/defaults/liberty-plugin-variable-config.xml does not contain expected variable: "+ libertyConfigVarDefaultsFile.text
        assert libertyConfigVarDefaultsFile.text.contains("defaultValue=\"someDefaultValue\"") : "configDropins/defaults/liberty-plugin-variable-config.xml does not contain expected variable: "+ libertyConfigVarDefaultsFile.text

    }
}
