package io.openliberty.tools.gradle


import org.junit.Assert
import org.junit.BeforeClass
import org.junit.FixMethodOrder
import org.junit.Test
import org.junit.runners.MethodSorters

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
class TestMergeServerEnvLtpa extends AbstractIntegrationTest {
    static File resourceDir = new File("build/resources/test/sample.servlet")
    static File buildDir = new File(integTestDir, "/test-merge-server-env-ltpa")
    static String buildFilename = "testMergeServerEnvLtpa.gradle"

    @BeforeClass
    public static void setup() {
        createDir(buildDir)
        createTestProject(buildDir, resourceDir, buildFilename)
        runTasks(buildDir, 'libertyCreate')
    }

    @Test
    public void check_for_server_env() {
        assert new File('build/testBuilds/test-merge-server-env-ltpa/build/wlp/usr/servers/LibertyProjectServer/server.env').exists() : 'server.env not found!'
    }

    /**
     * Test that ltpa_keys_password is automatically generated by Liberty 26.0.0.4 and merged.
     * 
     * This is the key test - verifying that:
     * 1. Liberty 26.0.0.4 auto-generates ltpa_keys_password in default server.env
     * 2. The auto-generated ltpa_keys_password is preserved during merge
     * 3. User-provided properties are also merged correctly
     * 
     * Final expected values:
     * - keystore_password: <auto-generated by Liberty 26.0.0.4>
     * - ltpa_keys_password: <auto-generated by Liberty 26.0.0.4> - THIS IS THE KEY VERIFICATION
     * - TEST_PROP_1: fromEnvProps
     * - CUSTOM_PROP: customValue
     */
    @Test
    public void check_ltpa_keys_password_auto_generated() {
        File serverEnv = new File("build/testBuilds/test-merge-server-env-ltpa/build/wlp/usr/servers/LibertyProjectServer/server.env")
        
        Map<String,String> serverEnvContents = new HashMap<String,String>();

        BufferedReader bf = new BufferedReader(new FileReader(serverEnv))
        String line = bf.readLine();
        boolean commentFound = false
        while(line != null) {
            //ignore comment lines
            if(!line.startsWith("#") && !line.trim().isEmpty()) {
                String[] keyValuePair = line.split("=", 2);
                if (keyValuePair.length == 2) {
                    String key = keyValuePair[0].trim();
                    String value = keyValuePair[1].trim();
                    serverEnvContents.put(key, value);
                }
            } else if (line.startsWith("#")) {
                if (line.contains("liberty-gradle-plugin")) {
                    commentFound = true
                }
            }
            line = bf.readLine();
        }
        
        // Verify the file was generated by liberty-gradle-plugin
        Assert.assertTrue("Expected 'Generated by liberty-gradle-plugin' comment not found", commentFound);
        
        // Verify keystore_password from Liberty 26.0.0.4 is preserved
        Assert.assertTrue("keystore_password should be present (auto-generated by Liberty 26.0.0.4)", 
                serverEnvContents.containsKey("keystore_password"));
        
        // KEY VERIFICATION: ltpa_keys_password should be present and auto-generated by Liberty 26.0.0.4
        Assert.assertTrue("ltpa_keys_password should be present (auto-generated by Liberty 26.0.0.4)", 
                serverEnvContents.containsKey("ltpa_keys_password"));
        
        // Verify ltpa_keys_password has a non-empty value (auto-generated)
        Assert.assertFalse("ltpa_keys_password should have a non-empty auto-generated value", 
                serverEnvContents.get("ltpa_keys_password").isEmpty());
        
        // Verify other merged properties
        Assert.assertTrue("TEST_PROP_1 should be present from envProps", 
                serverEnvContents.containsKey("TEST_PROP_1"));
        Assert.assertEquals("TEST_PROP_1 should have value from envProps", 
                "fromEnvProps", serverEnvContents.get("TEST_PROP_1"));
        
        Assert.assertTrue("CUSTOM_PROP should be present from build.gradle", 
                serverEnvContents.containsKey("CUSTOM_PROP"));
        Assert.assertEquals("CUSTOM_PROP should have value from build.gradle", 
                "customValue", serverEnvContents.get("CUSTOM_PROP"));
        
        // Verify minimum number of properties (auto-generated + user-provided)
        Assert.assertTrue("Number of env properties should be >= 4, but is " + serverEnvContents.size(), 
                serverEnvContents.size() >= 4);
    }

    /**
     * Test that both special properties (keystore_password and ltpa_keys_password) 
     * are auto-generated by Liberty 26.0.0.4 and preserved during merge.
     */
    @Test
    public void check_both_special_properties_auto_generated() {
        File serverEnv = new File("build/testBuilds/test-merge-server-env-ltpa/build/wlp/usr/servers/LibertyProjectServer/server.env")
        
        Map<String,String> serverEnvContents = new HashMap<String,String>();

        BufferedReader bf = new BufferedReader(new FileReader(serverEnv))
        String line = bf.readLine();
        while(line != null) {
            if(!line.startsWith("#") && !line.trim().isEmpty()) {
                String[] keyValuePair = line.split("=", 2);
                if (keyValuePair.length == 2) {
                    String key = keyValuePair[0].trim();
                    String value = keyValuePair[1].trim();
                    serverEnvContents.put(key, value);
                }
            }
            line = bf.readLine();
        }
        
        // Both special properties should be present (auto-generated by Liberty 26.0.0.4)
        Assert.assertTrue("keystore_password should be auto-generated by Liberty 26.0.0.4", 
                serverEnvContents.containsKey("keystore_password"));
        Assert.assertTrue("ltpa_keys_password should be auto-generated by Liberty 26.0.0.4", 
                serverEnvContents.containsKey("ltpa_keys_password"));
        
        // Verify both have non-empty values
        Assert.assertFalse("keystore_password should have a non-empty auto-generated value", 
                serverEnvContents.get("keystore_password").isEmpty());
        Assert.assertFalse("ltpa_keys_password should have a non-empty auto-generated value", 
                serverEnvContents.get("ltpa_keys_password").isEmpty());
    }

    /**
     * Test that the merge preserves auto-generated ltpa_keys_password along with user properties.
     * This verifies the mergeSpecialPropsFromInstallServerEnvIfAbsent functionality.
     */
    @Test
    public void check_auto_generated_ltpa_password_preserved_during_merge() {
        File serverEnv = new File("build/testBuilds/test-merge-server-env-ltpa/build/wlp/usr/servers/LibertyProjectServer/server.env")
        
        Map<String,String> serverEnvContents = new HashMap<String,String>();

        BufferedReader bf = new BufferedReader(new FileReader(serverEnv))
        String line = bf.readLine();
        while(line != null) {
            if(!line.startsWith("#") && !line.trim().isEmpty()) {
                String[] keyValuePair = line.split("=", 2);
                if (keyValuePair.length == 2) {
                    String key = keyValuePair[0].trim();
                    String value = keyValuePair[1].trim();
                    serverEnvContents.put(key, value);
                }
            }
            line = bf.readLine();
        }
        
        // Verify ltpa_keys_password is present (auto-generated and preserved)
        Assert.assertTrue("ltpa_keys_password should be preserved from Liberty 26.0.0.4 auto-generation", 
                serverEnvContents.containsKey("ltpa_keys_password"));
        
        // Verify user properties are also present (proving merge worked)
        Assert.assertTrue("TEST_PROP_1 should be merged from envProps", 
                serverEnvContents.containsKey("TEST_PROP_1"));
        Assert.assertTrue("CUSTOM_PROP should be merged from build.gradle", 
                serverEnvContents.containsKey("CUSTOM_PROP"));
        
        // This proves that auto-generated ltpa_keys_password was preserved during merge
        Assert.assertEquals("TEST_PROP_1 value should be correct", 
                "fromEnvProps", serverEnvContents.get("TEST_PROP_1"));
        Assert.assertEquals("CUSTOM_PROP value should be correct", 
                "customValue", serverEnvContents.get("CUSTOM_PROP"));
    }
}