package io.openliberty.tools.gradle;

import java.io.File
import java.io.FileInputStream;
import java.util.Properties;

import org.junit.BeforeClass
import org.junit.Test
import org.apache.commons.io.FileUtils
import io.openliberty.tools.common.plugins.util.OSUtil

public class TestCreateWithInlineProperties extends AbstractIntegrationTest{
    static File sourceDir = new File("build/resources/test/server-config-files")
    static File testBuildDir = new File(integTestDir, "/test-create-with-inline-properties")
    static String buildFilename = "testCreateLibertyInlineProperties.gradle"

    @BeforeClass
    public static void setup() {
        createDir(testBuildDir)
        createTestProject(testBuildDir, sourceDir, buildFilename, true)
    }

    @Test
    public void test_create_with_inline_properties() {

        runTasks(testBuildDir, 'libertyCreate')

        def bootstrapFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/bootstrap.properties")
        def jvmOptionsFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/jvm.options")
        def configFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/server.xml")
        def serverEnvFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/server.env")
        def libertyConfigVarFile = new File("build/testBuilds/test-create-with-inline-properties/build/wlp/usr/servers/LibertyProjectServer/configDropins/overrides/liberty-plugin-variable-config.xml")

        assert bootstrapFile.exists() : "file not found"
        assert jvmOptionsFile.exists() : "file not found"
        assert configFile.exists() : "file not found"
        assert serverEnvFile.exists() : "file not found"
        assert libertyConfigVarFile.exists() : "file not found"

        if (OSUtil.isWindows()) {
            assert jvmOptionsFile.text.startsWith("# Generated by liberty-gradle-plugin\r\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
            assert jvmOptionsFile.text.endsWith("-Xmx2048m\r\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
            assert jvmOptionsFile.text.contains("-Xmx512m\r\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
            assert jvmOptionsFile.text.contains("-Xms128m\r\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
        } else {
            assert jvmOptionsFile.text.startsWith("# Generated by liberty-gradle-plugin\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
            assert jvmOptionsFile.text.endsWith("-Xmx2048m\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
            assert jvmOptionsFile.text.contains("-Xmx512m\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
            assert jvmOptionsFile.text.contains("-Xms128m\n") : "jvm inline options did not copy properly "+jvmOptionsFile.text
        }

        assert FileUtils.contentEquals(configFile, new File("build/testBuilds/test-create-with-inline-properties/src/main/liberty/config/server.xml")) : "server.xml file did not copy properly"


        // Verify the bootstrap.properties file contains correct info from inline config
        FileInputStream input1 = new FileInputStream(bootstrapFile);

        Properties prop = new Properties();
        prop.load( input1 );
        String value1 = prop.getProperty("default.http.port");
        assert value1 != null : "bootstrap property not found"
        assert value1.equals("9083") : "bootstrap property has incorrect value"

        value1 = prop.getProperty("default.https.port");
        assert value1 != null : "bootstrap property not found"
        assert value1.equals("9474") : "bootstrap property has incorrect value"


        FileInputStream input2 = new FileInputStream(serverEnvFile);

        prop = new Properties();
        prop.load( input2 );
        assert prop.size() == 2 : "expected 2 properties in server.env file but found "+prop.size()
        String value2 = prop.getProperty("some.env.var");
        assert value2 != null && value2.equals("someValue") : "property not found in server.env file"
        value2 = prop.getProperty("another.env.var");
        assert value2 != null && value2.equals("anotherValue") : "property not found in server.env file"
    }
}
