
FROM icr.io/appcafe/open-liberty:kernel-slim-java21-openj9-ubi-minimal

LABEL \
  org.opencontainers.image.authors="Your Name" \
  org.opencontainers.image.vendor="IBM" \
  org.opencontainers.image.url="local" \
  org.opencontainers.image.source="https://github.com/OpenLiberty/guide-docker" \
  org.opencontainers.image.version="$VERSION" \
  org.opencontainers.image.revision="$REVISION" \
  vendor="Open Liberty" \
  name="system" \
  version="$VERSION-$REVISION" \
  summary="The system microservice from the Docker Guide" \
  # tag::description[]
  description="This image contains the system microservice running with the Open Liberty runtime."
  # end::description[]
# end::label[]

COPY --chown=1001:0 /src/main/liberty/config /config

RUN features.sh

COPY --chown=1001:0 build/libs/*.war /config/apps

RUN configure.sh
